name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    permissions:
      contents: read
      deployments: write    
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2

    - name: Build Swift package
      run: swift build --configuration release

    - name: Run Swift package
      run: .build/release/SooKimTWL

    - name: Copy existing files
      run: |
        cp google70dd4382a6eecd18.html ./Build/
        cp robots.txt ./Build/
        cp naver50ba38ef6c02338f50a2369f3010ed59.html ./Build/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: sookim-1/sookim-1.github.io
        publish_branch: main
        publish_dir: ./Build/
