name: CI

on:
  push:
    branches: [ main ]
    
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: swift:5.6-focal
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        swift --version
        swift package --version
        swift build -v

  generate-website:
    runs-on: ubuntu-20.04
    container:
      image: swift:5.6-focal
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: make setup
    - name: Generate the website
      run: make generate
