name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: "swift:5.6"
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        swift --version
        swift package --version
        swift build -v

  generate-website:
    runs-on: ubuntu-latest
    container: "swift:5.6"
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: make setup
    - name: Generate the website
      run: make generate
    - name: github.io 배포
      uses: actions/workflow-dispatch@v2
      with:
        workflow: ./.github/workflows/depoly.yml
